### ISSUE TITLE
would there be any demo codes?

### ISSUE THREAD

**Issue by chophilip21** [minjoong507/BM-DETR#3]
Hi,

Thanks a lot for your great work. I was just wondering if you have any plans to introduce a demo code?

Something like gradio demo code would be great in terms of testing your work.

Thanks!

**Comment by minjoong507** [comment]
Hi @chophilip21,

Thanks for your interest in our work and suggestions.

For now, we don't have a plan for releasing demo codes.

Please let me know if there is something that I can assist you with.

Thank you.
